# Generated by Django 4.2.21 on 2025-06-05 08:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("receipts", "0002_receipt_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="receipt",
            name="category",
            field=models.CharField(default="その他", max_length=50),
        ),
        migrations.AddField(
            model_name="receipt",
            name="logo_confidence",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="receipt",
            name="store_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
