# Generated by Django 4.2.21 on 2025-06-19 11:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("receipts", "0003_receipt_category_receipt_logo_confidence_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="receipt",
            name="shop_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
