# Generated by Django 4.2.21 on 2025-06-19 11:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("receipts", "0004_receipt_shop_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="receipt",
            name="total_amount",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
