# Generated by Django 4.2.21 on 2025-06-20 05:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("receipts", "0005_receipt_total_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="receipt",
            name="memo",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="receipt",
            name="purchase_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="receipt",
            name="category",
            field=models.CharField(
                blank=True, default="その他", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="receipt",
            name="shop_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="receipt",
            name="store_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="receipt",
            name="total_amount",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="receipt",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
