# Generated by Django 4.2.23 on 2025-06-24 05:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("receipts", "0006_receipt_memo_receipt_purchase_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="receipt",
            name="issue_date",
            field=models.DateField(blank=True, null=True, verbose_name="発行日"),
        ),
    ]
